### ISSUE TITLE
Alertコンポーネントの拡張

### ISSUE THREAD

**Issue by hajime-matsumoto** [hirotomoyamada/yamada-ui#203]
### 概要

Alertコンポーネントにステータス=infoのように設定できるところから、Admonition的な使い方を想定しているように、見受けられるのですが、Alert status=info のようなコードは可読性的に、誤解を招く(システム上Alertという文言は強い意味合いを持つため)不適切なように感じます。

### 問題の主張/正当化

コーディングの概念として、人間にも機械にも可読性を高めるという原則があるので、誤用される可能性を少なくなるようにしたほうがいいかと思います。

### 提案する解決策やAPI

Alertではなく、MessageBlock, Admonitionのようなコンポーネント名にしたほうがいいかと思います。また、デザインにかんしても、 

<pre>
(i) 注釈です
----------------
詳細詳細
</pre>

のようなサンプルも追加してほしいです。

**Comment by hirotomoyamada** [comment]
UIコンポーネントライブラリとして、他のUIコンポーネントライブラリとコンポーネント名を合わせることは責務だと感じます。他のUIコンポーネントライブラリで同機能のものは、`Alert`と呼称しているのでYamada UIも同様に呼称していこうと思います。

- [Chakra UI - Alert](https://chakra-ui.com/docs/components/alert)
- [Mantine - Alert](https://mantine.dev/core/alert/)
- [Material UI - Alert](https://mui.com/material-ui/react-alert/)

ただ、`status="info"`とお知らせのような表示を`Alert`コンポーネントで表現するのは不適切だと私も感じるので、`v2`あたりでコミュニティと協議し方向性を決めたいと感じます。
