### ISSUE TITLE
Enable to select any range of dates with `DatePicker` or `Calendar`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#254]
### Description

Currently, `Calendar` allows multiple selection of dates, but it is not possible to select a range of days.

### Problem Statement/Justification

Depending on the project, you may want to select a range of dates from one day to the next. I feel this is an essential feature.

**Comment by matsu3m** [comment]
Hi, may I take on this issue?
Also, what is the planned release date for v1.2?
Thanks!

**Comment by hirotomoyamada** [comment]
@matsu3m 

Hey, thanks for the comment.

Sorry, I'm already working on this issue.

However, I plan to add othbr issues, so please wait.

**Comment by matsu3m** [comment]
I had a hunch that you might be tackling this issue, after your recent update on the Calendar. I'm glad I asked.
Let me know if there's anything else I can assist with!
