### ISSUE TITLE
The `className` defined in `columns` of the `Table` component is not reflected in `Th`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#263]
### Description

When I defined `className` in the `columns` of the `Table` component, I thought that the `className` would be reflected in `Th`, but the `className` was not reflected in `Th`.

### Yamada UI Version

0.8.24

### Browser

Google Chrome 119

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by Dhoni77** [comment]
Hi I would like to work on this

**Comment by hirotomoyamada** [comment]
@Dhoni77 Please do it!!!!!!
