### ISSUE TITLE
Add tests for `@yamada-ui/notice`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#349]
related: #74

### Description

Currently, no tests in `@yamada-ui/notice`. In the future, I feel the need for testing when operating `@yamada-ui/notice`.

### Problem Statement/Justification

Testing is essential to ensure quality when operating a package.

**Comment by 108yen** [comment]
これやってもいいでしょうか？

**Comment by hirotomoyamada** [comment]
@108yen 

こんにちは！

ぜひ、やってほしいです。

アサインをあなたに割り当てます。幸運を！
