### ISSUE TITLE
Add tests for `@yamada-ui/pin-input`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#352]
related: #74

### Description

Currently, no tests in `@yamada-ui/pin-input`. In the future, I feel the need for testing when operating `@yamada-ui/pin-input`.

### Problem Statement/Justification

Testing is essential to ensure quality when operating a package.

**Comment by 000000armor** [comment]
Hi @hirotomoyamada ! I'd love to work on this one

**Comment by hirotomoyamada** [comment]
@000000armor 

Hi, thanks for the comment.

Yes, please.

Good luck!
