### ISSUE TITLE
Add tests for `@yamada-ui/popover`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#353]
related: #74

### Description

Currently, no tests in `@yamada-ui/popover`. In the future, I feel the need for testing when operating `@yamada-ui/popover`.

### Problem Statement/Justification

Testing is essential to ensure quality when operating a package.

**Comment by kirikirisu** [comment]
@hirotomoyamada 
Hi! Can I work on this Issue?

**Comment by hirotomoyamada** [comment]
@kirikirisu 

Hi, thanks for the comment!

Yes, please!

I will assign this issue to you. Good luck!
