### ISSUE TITLE
Add tests for `@yamada-ui/reorder`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#357]
related: #74

### Description

Currently, no tests in `@yamada-ui/reorder`. In the future, I feel the need for testing when operating `@yamada-ui/reorder`.

### Problem Statement/Justification

Testing is essential to ensure quality when operating a package.

**Comment by 000000armor** [comment]
Hi @hirotomoyamada ! Can I work on this one?

**Comment by hirotomoyamada** [comment]
@000000armor 

Hi, thanks for the comment!

Yes, please.

i'll assign this issue to you.
