### ISSUE TITLE
Add tests for `@yamada-ui/stepper`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#363]
related: #74

### Description

Currently, no tests in `@yamada-ui/stepper`. In the future, I feel the need for testing when operating `@yamada-ui/stepper`.

### Problem Statement/Justification

Testing is essential to ensure quality when operating a package.

**Comment by 000000armor** [comment]
@hirotomoyamada 
Hi! Can I work on this one?

**Comment by hirotomoyamada** [comment]
Hi, thanks for the comment!

Yes, please. I'll assign this issuse to you.
