### ISSUE TITLE
IDs used in ARIA and labels must be unique

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#473]
### Which package has an issue?

@yamada-ui/react

### Package Version

0.9.2

### Description

If you wrap a `RadioGroup` or `CheckboxGroup` with a `FormControl`, the ids are duplicated.

### Steps to Reproduce

1.  Wrap a `RadioGroup` or `CheckboxGroup` with a `FormControl`.
2. Duplicate IDs are set for child elements.

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by matsu3m** [comment]
I'd like to work on this issue. Starting now, thanks!
