### ISSUE TITLE
Elements must only use allowed ARIA attributes

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#474]
### Which package has an issue?

@yamada-ui/react

### Package Version

0.9.2

### Description

When setting `isReadonly` to `Switch` or `Select` components, `aria-readonly` is assigned to unnecessary elements.

### Steps to Reproduce

1. Set `isReadonly` to `Switch` or `Select` components.
2. Assigned `aria-readonly` to element.
3. `aria-readonly` is assigned to unnecessary elements.

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by teru12012000** [comment]
@hirotomoyamada 
Hello!!!
I want to challenge this issue.
