### ISSUE TITLE
dayjs locale変換不具合

### ISSUE THREAD

**Issue by nthhm** [hirotomoyamada/yamada-ui#515]
### どのパッケージに問題がありますか？

@yamada-ui/calendar

### パッケージのバージョン

0.9.7

### 概要

カレンダーなどのday.jsで曜日を表示するコンポーネントにおいて、`locale="ja"`を指定した時に正しく変換処理が行われていない

### 再現手順

1. `pnpm storybook`でstorybookを立ち上げる.
2. Data Display => Calendar => With Format を確認.
3. 最後のコンポーネントの曜日表示が以下になっていることを確認.

![スクリーンショット 2023-12-20 20 25 51](https://github.com/hirotomoyamada/yamada-ui/assets/44593742/baada4da-4fa8-4973-a775-ab8d89bbb467)

### ブラウザ

Chrome

### OS

- [X] macOS
- [ ] Windows
- [ ] Linux

### まさか、問題の修正方法をご存知ですか？

はい

### この問題の修正に参加し、修正を含むプルリクエストを作成する志はありますか？

はい

### 追加情報

現状有効であった解決方法としては、`use-calendar.ts`の`getWeekdays`関数内でlocaleの値に応じてday.jsの言語プラグインを用いてグローバルにロケールを変換する方法です.
ただし、多言語対応の想定した時に冗長になるため構成を検討している段階です.

```javascript
import ja from "dayjs/locale/ja"

export const getWeekdays = (

  // 省略 ...

  const date = getFirstOfWeek(new Date(), firstDayOfWeek)

  if (locale === "ja") dayjs.locale(ja) // localeの値に応じてglobalに変換

  for (let i = 0; i < 7; i += 1) {
    const weekday = dayjs(date).locale(locale).format(format)

    weekdays = [...weekdays, weekday]

　// ... 省略



```

**Comment by hirotomoyamada** [comment]
@nthhm 

こんにちは！

結論からお話すると、`yamada-ui`のルートでインストールされている`dayjs`と`@yamada-ui/calendar`でインストールされている`dayjs`のバージョンが一致していないことが原因です。

- `yamada-ui`: `1.11.10`
- `@yamada-ui/calendar`: `1.11.7`

これを解決するのは、`yamada-ui`の`dayjs`のバージョンを下げるか、`@yamada-ui/calendar`の`dayjs`のバージョンを上げるか、です。

私は、後者の

> `@yamada-ui/calendar`の`dayjs`のバージョンを上げる

にしたいと思っています。

**Comment by hirotomoyamada** [comment]
`dayjs`は、`import "dayjs/locale/ja"`などでロケールをインポートした場合、ファイル内で`dayjs.locale(locale, null, true)`を実行します。実行後、`index.js`の`const Ls = {}`に格納され、生成されるインスタンスは`Ls`を参照します。

```title=locale/ja.js
// Japanese [ja]
import dayjs from 'dayjs'

const locale = {
  name: 'ja',
  weekdays: '日曜日_月曜日_火曜日_水曜日_木曜日_金曜日_土曜日'.split('_'),
  weekdaysShort: '日_月_火_水_木_金_土'.split('_'),
  weekdaysMin: '日_月_火_水_木_金_土'.split('_'),
  months: '1月_2月_3月_4月_5月_6月_7月_8月_9月_10月_11月_12月'.split('_'),
  monthsShort: '1月_2月_3月_4月_5月_6月_7月_8月_9月_10月_11月_12月'.split('_'),
  ordinal: n => `${n}日`,
  formats: {
    LT: 'HH:mm',
    LTS: 'HH:mm:ss',
    L: 'YYYY/MM/DD',
    LL: 'YYYY年M月D日',
    LLL: 'YYYY年M月D日 HH:mm',
    LLLL: 'YYYY年M月D日 dddd HH:mm',
    l: 'YYYY/MM/DD',
    ll: 'YYYY年M月D日',
    lll: 'YYYY年M月D日 HH:mm',
    llll: 'YYYY年M月D日(ddd) HH:mm'
  },
  meridiem: hour => (hour < 12 ? '午前' : '午後'),
  relativeTime: {
    future: '%s後',
    past: '%s前',
    s: '数秒',
    m: '1分',
    mm: '%d分',
    h: '1時間',
    hh: '%d時間',
    d: '1日',
    dd: '%d日',
    M: '1ヶ月',
    MM: '%dヶ月',
    y: '1年',
    yy: '%d年'
  }
}

dayjs.locale(locale, null, true)

export default locale
```

```index.js
const parseLocale = (preset, object, isLocal) => {
  let l
  if (!preset) return L
  if (typeof preset === 'string') {
    const presetLower = preset.toLowerCase()
    if (Ls[presetLower]) {
      l = presetLower
    }
    if (object) {
      Ls[presetLower] = object
      l = presetLower
    }
    const presetSplit = preset.split('-')
    if (!l && presetSplit.length > 1) {
      return parseLocale(presetSplit[0])
    }
  } else {
    const { name } = preset
    Ls[name] = preset
    l = name
  }
  if (!isLocal && l) L = l
  return l || (!isLocal && L)
}
```
