### ISSUE TITLE
Elements must only use allowed ARIA attributes

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#591]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.1.2

### Description

When setting `isReadonly` to `DatePicker` or `MouthPicker` components, `aria-readonly` is assigned to unnecessary elements.

### Target Components

- `DatePicker`
- `MonthPicker`
- `SegmentedControl`
- `MultiAutocomplete`
- `Autocomplete`
- `PinInput`
- `NativeSelect`

### Link to Reproduction

1. Set `isReadonly` to `Switch` or `Select` components. 2. Assigned `aria-readonly` to element. 3. `aria-readonly` is assigned to unnecessary elements.

### Steps to Reproduce

1. Set `isReadonly` to `Switch` or `Select` components.
2. Assigned `aria-readonly` to element.
3. `aria-readonly` is assigned to unnecessary elements.

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by ISAWASHUN** [comment]
@hirotomoyamada 

Nice to meet you, I'm currently a college student doing Rails as an intern, and I found this issue through Zenn's article.
I have no practical experience with Next.js, but I would like to try OSS.
May I work on this issue?

<details><summary>日本語訳</summary>
<p>
初めまして、現在大学生でインターンでRailsを行っているものです。Zennの記事を見てこのissueを発見しました。
Next.jsは実務で経験がないですが、OSS活動に挑戦したいと思っています。
このissueに取り組んでもよろしいでしょうか。
</p>
</details>

**Comment by hirotomoyamada** [comment]
@ISAWASHUN

こんにちは。はじめまして！ぜひ、OSSに参加してみましょう！このイシューを取り組んでみましょう！

Let's Try!!!

**Comment by ISAWASHUN** [comment]
@hirotomoyamada 

ありがとうございます！
取り組みます！

**Comment by hirotomoyamada** [comment]
こんにちは！

#584 
#574 
#545

このPRを参考にすると良いと思います。やっていることは、同じ作業です。

また、`aria-readonly`が不要な要素を発見するには、各コンポーネントの[Story](https://hirotomoyamada.github.io/yamada-ui/?path=/story/components-forms-datepicker--is-readonly)の`Accessibility`を見ると良いでしょう。

**Comment by hirotomoyamada** [comment]
@ISAWASHUN 

こんにちは！

#584 
#574 
#545

このPRを参考にすると良いと思います。やっていることは、同じ作業です。

また、`aria-readonly`が不要な要素を発見するには、各コンポーネントの[Story](https://hirotomoyamada.github.io/yamada-ui/?path=/story/components-forms-datepicker--is-readonly)の`Accessibility`を見ると良いでしょう。

**Comment by ISAWASHUN** [comment]
@hirotomoyamada 

アドバイスありがとうございます！
今日の夜から本格的に進めていきます！

**Comment by hirotomoyamada** [comment]
@ISAWASHUN 

こんにちは！

このイシューの状況は、どうですか？

明日、このイシューのアサインを初期の状態に戻します。

このイシューを取り組んでおり、延長する場合は、こちらに連絡をください。

**Comment by ISAWASHUN** [comment]
@hirotomoyamada 

卒論と上京準備でバタバタしてたので、取り組めてませんでした。
ご迷惑をお掛けして申し訳ないです。外してもらって大丈夫です。
申し訳ございません。

**Comment by hirotomoyamada** [comment]
@ISAWASHUN

Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.

If you are working on this issue and would like to be reassigned, please contact us.

**Comment by apple-yagi** [comment]
@hirotomoyamada 

Hi there! I'm interested in working on this issue.
Is it okay if I take on this task?

**Comment by hirotomoyamada** [comment]
@apple-yagi 

Hi, thanks for the comment!

Yes, please!

I will assign this issue to you, Good luck!
