### ISSUE TITLE
bug: tooltip label close when click on children of tooltip

### ISSUE THREAD

**Issue by quangnmwork** [hirotomoyamada/yamada-ui#603]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.1.4

### Description

When click on children of the Tooltip component, the label will close when we click it.

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-jthudx?file=src%2FApp.tsx,src%2Findex.tsx

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

Video bug: 

https://github.com/hirotomoyamada/yamada-ui/assets/78476413/16833213-add9-4508-b8ee-820ec554dc7b

**Comment by hirotomoyamada** [comment]
@quangnmwork

Hey, thanks for the issue! I would like to ask you to do this work.
