### ISSUE TITLE
`MultiAutocomplete` JSDoc default value is wrong

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#609]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.1.5

### Description

The default value of `closeOnSelect` in `MultiAutocomplete` component's JSDoc is `true`, but it should be `false`.

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by KenyaMasuko** [comment]
Hi, thanks for this useful software !

I have no experience contributing to OSS, but I want to try contributing to Yamada UI.
May I take on this issue?

**Comment by hirotomoyamada** [comment]
@KenyaMasuko 

Hi, thanks for the comment!

Yes, please!

I'll assign this issue to you. Good luck!
