### ISSUE TITLE
Add tests for `@yamada-ui/rating`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#624]
related: #74

### Description

Currently, no tests in `@yamada-ui/rating`. In the future, I feel the need for testing when operating `@yamada-ui/rating`.

### Problem Statement/Justification

Testing is essential to ensure quality when operating a package.

**Comment by illionillion** [comment]
I will do it.

**Comment by hirotomoyamada** [comment]
@sora33 

Hi, thanks for the comment!

Yes, please! Assign to you. Good luck!
