### ISSUE TITLE
Add tests for `@yamada-ui/stat`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#625]
related: #74

### Description

Currently, no tests in `@yamada-ui/stat`. In the future, I feel the need for testing when operating `@yamada-ui/stat`.

### Problem Statement/Justification

Testing is essential to ensure quality when operating a package.

**Comment by Evande1** [comment]
can i work on this issue?

**Comment by hirotomoyamada** [comment]
Hi, thanks for the comment!

Yes, please! Assign to you. Good luck!
