### ISSUE TITLE
`Tooltip` component `onClose` prop fires both when `Tooltip` component opens and closes

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#630]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.1.7

### Description

I have a `Tooltip` component like so:

`<Tooltip hasArrow onClose={() => console.log('closed')}...`

When the `Tooltip` opens, the `onClose` prop gets fired, triggering the console log.

### Steps to Reproduce

1. Hover over `Tooltip` component.
2. Observe the console to see "closed" being logged when the tooltip opens instead of on close.

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### `tooltip.tsx`

```tsx
const openWithDelay = useCallback(() => {
  if (!isDisabled && !openTimeout.current) {
    closeNow()

    const win = getOwnerWindow(triggerRef.current)

    openTimeout.current = win.setTimeout(onOpen, openDelay)
  }
}, [isDisabled, openDelay, closeNow, onOpen])
```

to

```tsx
const openWithDelay = useCallback(() => {
  if (!isDisabled && !openTimeout.current) {
    if (isOpen) closeNow()

    const win = getOwnerWindow(triggerRef.current)

    openTimeout.current = win.setTimeout(onOpen, openDelay)
  }
}, [isDisabled, isOpen, openDelay, closeNow, onOpen])
```

**Comment by madangopal16072000** [comment]
can i work on this issue.

**Comment by hirotomoyamada** [comment]
@madangopal16072000 

Hi, thanks for the comment!

Yes, please!

I'll assign this issue to you. Good luck!
