### ISSUE TITLE
`fontSize` of excessive numbers in `AvatarGroup` is not set to theme `sizes`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#631]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.1.7

### Description

When the `size` of `AvatarGroup` is set to `xs` or `2xs`, the display is distorted because the `fontSize` of the excessive number does not exist in the theme `sizes`.

### Steps to Reproduce

1. Set `size` with `xs` to `AvatarGroup`
2. See excessive number element

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### `theme/src/components/avatar.ts`

```tsx
sizes: {
  "2xs": ({ theme: t }) => ({
    container: {
      w: "4",
      h: "4",
      fontSize: `calc(${get(t, "sizes.4")} / 2.5)`,
    },
    name: {
      fontSize: `calc(${get(t, "sizes.4")} / 2.5)`,
      lineHeight: get(t, "sizes.16"),
    },
    excess: {
      w: "4",
      h: "4",
    },
  }),
  ...
}
```

to

```tsx
sizes: {
  "2xs": ({ theme: t }) => ({
    container: {
      w: "4",
      h: "4",
      fontSize: `calc(${get(t, "sizes.4")} / 2.5)`,
    },
    name: {
      fontSize: `calc(${get(t, "sizes.4")} / 2.5)`,
      lineHeight: get(t, "sizes.16"),
    },
    excess: {
      w: "4",
      h: "4",
      fontSize: `calc(${get(t, "sizes.4")} / 2.5)`,
      lineHeight: get(t, "sizes.16"),
    },
  }),
  ...
}
```

**Comment by go-to-the-future** [comment]
初めまして！こちらのissueのPRを作成しても良いでしょうか

**Comment by hirotomoyamada** [comment]
@go-to-the-future 

こんばんは、はじめまして！

ぜひ、お願いします。

あなたにアサインを割り当てます。幸運を！

**Comment by hirotomoyamada** [comment]
@go-to-the-future 

こんにちは！

このイシューの状況は、どうですか？

明日、このイシューのアサインを初期の状態に戻します。

このイシューを取り組んでおり、延長する場合は、こちらに連絡をください。

**Comment by hirotomoyamada** [comment]
アサインを外します。

**Comment by hirotomoyamada** [comment]
@go-to-the-future

Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.

If you are working on this issue and would like to be reassigned, please contact us.

**Comment by hirotomoyamada** [comment]
@go-to-the-future

Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.

If you are working on this issue and would like to be reassigned, please contact us.
