### ISSUE TITLE
Support `::first-latter` and `::first-line`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#633]
### Description

`::first-latter` and `::first-line` are currently not supported.

### Problem Statement/Justification

```
_firstLatter: "&::first-latter",
_firstLine: "&::first-line"
```

**Comment by hirotomoyamada** [comment]
@illionillion 

Assign to you (:

**Comment by illionillion** [comment]
@hirotomoyamada `::first-letter`?
