### ISSUE TITLE
The JSDoc of the `_valid` pseudo-class is incorrect.

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#637]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.1.7

### Description

The JSDoc description is `:invalid`. Correctly, it is `:valid`.

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

```ts
  /**
   * The CSS `:valid` pseudo-class.
   */
  _valid: "&:valid, &[data-valid], &[data-state=valid]",
```

**Comment by hoshico** [comment]
@hirotomoyamada 
初めまして！
こちらのissueいただいてもよろしいでしょうか？？

**Comment by hirotomoyamada** [comment]
@hoshico 

こんにちは、はじめまして！

ぜひ、お願いします！

アサインをあなたに割り当てます。Good luck!
