### ISSUE TITLE
Clicking on `Rating` Component While Hovering Does Not Maintain Clicked State

### ISSUE THREAD

**Issue by illionillion** [hirotomoyamada/yamada-ui#640]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.0.5

### Description

When clicking on the Rating component while hovering on the edge, the expected behavior is observed as the click action occurs, but upon removing the hover, the component reverts to its original state as if it was not clicked. Ideally, clicking while in the hovered state should result in the Rating icon staying in the clicked state.

https://github.com/hirotomoyamada/yamada-ui/assets/60034520/f75f3c3a-d65c-408e-9b52-a4bbe60e0be3

### Link to Reproduction

https://hirotomoyamada.github.io/yamada-ui/?path=/story/components-forms-rating--basic

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

Yes
### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

Change the `onClick` part of the `getItemProps` function's return value at line 441 to `onMouseDown` and `onTouchStart`.

And, duplicate the onClick function at line 425, and change the duplicates to onMouseDown and onTouchStart respectively. Make necessary adjustments in other related sections accordingly.

```diff
return {
  ref,
  htmlFor: `${id}-${groupValue}-${value}`,
  ...formControlProps,
  ...props,
  zIndex: fractionValue !== 1 ? zIndex : undefined,
-  onClick: handlerAll(onClick, props.onClick),
+ onMouseDown: handlerAll(onMouseDown, props.onMouseDown),
+ onTouchStart: handlerAll(onTouchStart, props.onTouchStart),
  "data-active": dataAttr(isActive),
  "data-filled": dataAttr(isFilled),
  "data-focus": dataAttr(isFocused),
  "data-focus-visible": dataAttr(isFocused && isFocusVisible),
}```

**Comment by madangopal16072000** [comment]
can i work on this issue.

**Comment by hirotomoyamada** [comment]
Hi, thanks for the comment!

Yes, please!

Assign to you, good luck!
