### ISSUE TITLE
Alpha value is not displayed even if `defaultColor` is set

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#671]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.1

### Description

When you set `defaultColor` in `ColorPicker` component, You expected the alpha value to be displayed in `ColorSelector`, but it was not displayed.

### Link to Reproduction

https://hirotomoyamada.github.io/yamada-ui/?path=/story/components-forms-colorpicker--with-default-color

### Steps to Reproduce

1. Set `defaultColor` to `ColorPicker`.
2. Click on element and open the `ColorSelector`.
3. See `ColorSelector` component.

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

```diff
- const formatRef = useRef<ColorFormat>(format ?? calcFormat(value ?? ""))
+ const formatRef = useRef<ColorFormat>(format ?? calcFormat(value ?? defaultColor ?? ""))
```

**Comment by komura-c** [comment]
Hello, Can I try this Issue?
