### ISSUE TITLE
Closing menu scrolls back to its position

### ISSUE THREAD

**Issue by taroj1205** [hirotomoyamada/yamada-ui#674]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.1

### Description

When I close the menu, I expected to close without scrolling, but it scrolls back to the menu button position.

### Link to Reproduction

https://yamada-ui.com/components/overlay/menu

### Steps to Reproduce

1. Open the `<Menu />` by clicking on `<MenuButton />`
2. Scroll up/down until the `<MenuButton />` is hidden.
3. Close the `<Menu />` by clicking anywhere.
4. Scrolls back to the `<MenuButton />` as shown in the video in additional information.

### Browser

Edge

### Operating System

- [x] macOS
- [X] Windows
- [x] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

Recording of the issue: 

https://github.com/hirotomoyamada/yamada-ui/assets/61367823/3c8acf83-e47e-473a-9061-50739b57bd0e

**Comment by hirotomoyamada** [comment]
Hi, thanks for the issue.

By default, it returns to the previous focus position.

Please, set `restoreFocus` to `false`.
