### ISSUE TITLE
textareaにautosize機能追加

### ISSUE THREAD

**Issue by 108yen** [hirotomoyamada/yamada-ui#687]
### 概要

テキストの高さにtextareaの高さを自動で合わせる機能

### 問題の主張/正当化

長文が入力される場合に有用

### 提案する解決策やAPI

https://github.com/Andarist/react-textarea-autosize

**Comment by hirotomoyamada** [comment]
@108yen 

こんにちは！

この機能はとても良いアイディアだと思います。以前、私も同じことを構想しましたが、[field-sizing](https://github.com/whatwg/html/pull/9903)の件もあり、思考を放置しました。

しかし、新しいCSSはエージェントの対応云々があるのでJavaScriptで制御するのが無難だと思います。

**Comment by hirotomoyamada** [comment]
この機能を実装するにあたり、議論するべきなのは大きく分けて2点だと思います。

- `TextArea`の標準機能として実装する。
- `AutosizingTextArea`など、別のコンポーネントとして実装する。

また、両方の実装において、カスタマイズ(何行目までは高さを自動で調整するなど)できる`props`の考える必要があると思います。

**Comment by 108yen** [comment]
ありがとうございます！
賛成です！
[react-textarea-autosize](https://github.com/Andarist/react-textarea-autosize)の実装を参考にでよければやっていいですか？

**Comment by hirotomoyamada** [comment]
@108yen 

はい、そうですね。`react-textarea-autosize`を参考にして、実装してもらえればと思います。

実装は、108yenさんが取り組みますか？

**Comment by 108yen** [comment]
やります

**Comment by hirotomoyamada** [comment]
@108yen 

ありがとうございます！

では、アサインを割り当てます。
