### ISSUE TITLE
Add .idea and .coverage to .gitignore

### ISSUE THREAD

**Issue by 000000armor** [hirotomoyamada/yamada-ui#690]
### Description

Hi! It would be a good idea to add .idea and .coverage to the .gitignore file

### Problem Statement/Justification

I am using the popular IDE WebStorm by JetBrains, which creates a .idea folder with a bunch of settings files that I want to keep in the project folder. Additionally, when I run npx jest --coverage, it generates a .coverage folder, and I need to avoid adding them to the staging area for commits

### Proposed Solution or API

Add the .idea and .coverage folders to the .gitignore file

**Comment by hirotomoyamada** [comment]
Hi, thanks for the feature issue.

Is `.coverage` the wrong word for `coverage`? If it is `coverage`, it already exists in `.gitignore`.

`.idea` is a good suggestion. Could you please work on this issue?

Please set `.idea` in the same place as `.vscode`.

**Comment by hirotomoyamada** [comment]
@000000armor 

Hi, thanks for the feature issue.

Is `.coverage` the wrong word for `coverage`? If it is `coverage`, it already exists in `.gitignore`.

`.idea` is a good suggestion. Could you please work on this issue?

Please set `.idea` in the same place as `.vscode`.
