### ISSUE TITLE
The tests for each component have not been implemented yet.

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#74]
### Description

Perform tests on each component.

### Problem Statement/Justification

It is necessary to ensure quality during post-release changes as well.

### Proposed Solution or API

Place a "tests" folder in each package and perform testing within that folder.

**Comment by tecsoc** [comment]
Hi!
I'm inclined to help create the test (of course I can't do it all very well lol).
Do you have a specific type of test in mind, whether it is a visual regression test or a snapshot test?
Will you discuss/review that as well in the future?

**Comment by hirotomoyamada** [comment]
Fixed tests.
