### ISSUE TITLE
`IconButton` has `isRounded`, but `CloseButton` does not.

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#760]
### Description

`IconButton`'s props have `isRounded`, but `CloseButton` does not.

### Problem Statement/Justification

`CloseButton` should also be supported, since they have almost the same role.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by zvolcsey** [comment]
Hi! @hirotomoyamada Is this a good solution?

![closeButton](https://github.com/hirotomoyamada/yamada-ui/assets/41576384/deba0846-3dda-448e-aba3-73e14d564561)

I added this code to the css part of the `CloseButton` component.
```ts
...(isRounded ? { borderRadius: "9999px", border: "1px solid #000" } : {}),
```

**Comment by hirotomoyamada** [comment]
@zvolcsey 

Hi, thanks for the comment!

Yes, that code is correct.

**Comment by zvolcsey** [comment]
Hi! @hirotomoyamada Thanks for the answer!

I'll raise a PR today.
