### ISSUE TITLE
Cannot set `RangeSlider` thumb icons

### ISSUE THREAD

**Issue by taroj1205** [hirotomoyamada/yamada-ui#812]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.6

### Description

```tsx
  <RangeSlider
    thumbProps={{
      color: "blue.500",
      boxSize: "6",
      children: <Icon icon={faWaveSquare} />,
    }}
  />
  ```

I expect the `faWaveSquare` to be the thumb icon, but no icon is shown.

![https://media.discordapp.net/attachments/1114670052340416514/1210873186997116960/image.png?ex=65ec2488&is=65d9af88&hm=f4a5a38f4f575f835788a709e9619e20c79bc89e4d0be32d25ac1f6aad2be2df&=&format=webp&quality=lossless](https://media.discordapp.net/attachments/1114670052340416514/1210873186997116960/image.png?ex=65ec2488&is=65d9af88&hm=f4a5a38f4f575f835788a709e9619e20c79bc89e4d0be32d25ac1f6aad2be2df&=&format=webp&quality=lossless)

### Link to Reproduction

https://yamada-ui.com/components/forms/range-slider#customize-styling

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
```diff
export type RangeSliderThumbProps = HTMLUIProps<"div">

const RangeSliderThumb = forwardRef<
  RangeSliderThumbProps & { index: number },
  "div"
>(({ className, index, children, ...rest }, ref) => {
  const {
    styles,
    thumbProps,
    thumbColor,
    thumbSize,
    inputProps,
    getThumbProps,
    getInputProps,
  } = useRangeSliderContext()

  const css: CSSUIObject = { ...styles.thumb }

+  const { children: propChildren } = thumbProps ?? {}

  return (
    <ui.div
      className={cx("ui-slider__thumb", className)}
      __css={css}
      {...getThumbProps(
        {
          index,
          ...(thumbColor ? { bg: thumbColor } : {}),
          ...(thumbSize ? { boxSize: thumbSize } : {}),
          ...thumbProps,
          ...rest,
        },
        ref,
      )}
    >
      <ui.input {...getInputProps({ ...inputProps, index }, ref)} />
-       {children}
+      {children ?? propChildren}
    </ui.div>
  )
})
```

**Comment by Teramon1031** [comment]
こちらやります
