### ISSUE TITLE
Incorrect links to commit convention in CONTRIBUTING(.ja).md

### ISSUE THREAD

**Issue by Teramon1031** [hirotomoyamada/yamada-ui#820]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.6

### Description

When I clicked `commit convention` on `CONTRIBUTING.md`, I expected to be redirected to https://github.com/hirotomoyamada/yamada-ui/blob/main/CONTRIBUTING.md#commit-convention. However, in both the English and Japanese versions, I was taken to https://github.com/hirotomoyamada/yamada-ui/blob/main/README.md#commit-convention . 

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by june23hy** [comment]
はじめまして！
こちら修正したいです。

**Comment by hirotomoyamada** [comment]
@june23hy 

はじめまして！

お願いします！

アサインを割り当てます！幸運を！
