### ISSUE TITLE
The `Autocomplete` component references theme tokens for styling.

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#832]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.6

### Description

Yamada UI allows you to use components without applying a theme. It is a mistake to use theme tokens inside components.

```tsx
<ui.input
  className='ui-autocomplete__field__input'
  display='inline-block'
  w='full'
  placeholder={placeholder}
  {...getInputProps({ ...inputProps, value: inputValue || label || '' }, ref)}
/>
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by YuukiHayashi0510** [comment]
取り組んでみたいです！

**Comment by hirotomoyamada** [comment]
@YuukiHayashi0510 

こんにちは！

ぜひ、お願いします。

アサインを割り当てます。幸運を！

**Comment by hirotomoyamada** [comment]
@YuukiHayashi0510 

タイトルに誤りがありました。`Accordion`ではなく、`Autocomplete`です。

**Comment by YuukiHayashi0510** [comment]
以下のPRにて対応しました。ご確認のほど、よろしくお願いいたします！

#873
