### ISSUE TITLE
The `Skeleton` component references theme tokens for styling.

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#834]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.6

### Description

Yamada UI allows you to use components without applying a theme. It is a mistake to use theme tokens inside components.

`packages/components/skeleton/src/skeleton-circle.tsx`

```tsx
<Skeleton
  ref={ref}
  className={cx('ui-skeleton__circle', className)}
  rounded='full'
  isFitContent={isFitContent}
  {...(!isFitContent ? { boxSize } : {})}
  {...rest}>
  {validChildren}
</Skeleton>
```

`packages/components/skeleton/src/skeleton-text.tsx`

```tsx
const css: CSSUIObject = {
  w: 'full',
};
```

```tsx
{
  className,
  lineClamp = 3,
  startColor,
  endColor,
  fadeDuration,
  speed,
  isLoaded,
  gap = "2",
  textHeight = "2",
  children,
  ...rest
},
```

`packages/components/skeleton/src/skeleton.tsx`

```tsx
const css: CSSUIObject = {
  w: isFitContent ? 'fit-content' : 'full',
  maxW: 'full',
  h: isFitContent ? 'fit-content' : '4',
  boxShadow: 'none',
  backgroundClip: 'padding-box',
  cursor: 'default',
  color: 'transparent',
  pointerEvents: 'none',
  userSelect: 'none',
  '&::before, &::after, *': {
    visibility: 'hidden',
  },
  ...styles,
};
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by june23hy** [comment]
Hi! I committed in #876! 
Please check it out!

**Comment by hirotomoyamada** [comment]
@june23hy 

Hi, thanks for the comment and PR!

We check its PR.
