### ISSUE TITLE
The `Calendar` component references theme tokens for styling.

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#841]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.7

### Description

`packages/components/calendar/src/calendar-header.tsx`

```tsx
const css: CSSUIObject = {
  display: 'flex',
  alignItems: 'center',
  w: 'full',
  ...styles.header,
};
```

`packages/components/calendar/src/date-picker.tsx`

```tsx
<ui.input
  ref={mergeRefs(ref, inputRef)}
  className='ui-date-picker__field__input'
  display='inline-block'
  w='full'
  {...computedInputProps}
/>
```

`packages/components/calendar/src/month.tsx`

```tsx
<ui.th
  key={index}
  __css={{
    fontWeight: 'normal',
    ...styles.cell,
  }}
  {...thProps}>
  <ui.div
    className='ui-calendar__month__weekday'
    __css={{
      w: 'full',
      display: 'flex',
      ...styles.weekday,
    }}
    {...computedWeekdayProps}>
    {customWeekday({ weekday, index })}
  </ui.div>
</ui.th>
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by nogu66** [comment]
以下のプルリクエストにて対応しました。
https://github.com/hirotomoyamada/yamada-ui/pull/856
